### ISSUE TITLE
Parellelization

### ISSUE THREAD

**Issue by jeffjanes** [bashtanov/argm#2]
Are there any plans for implementing combining function and serial and deserial functions so that these aggregates can be used in parallel execution?

**Comment by bashtanov** [comment]
Looks doable. I'll do it when I have time (i.e. nobody knows how soon, sorry). Or, alternatively, everyone is welcome to open a PR for me to review.

**Comment by bashtanov** [comment]
Hello @jeffjanes, it's been almost a year since you requested this improvement, sorry for being so slow. This is to confirm that I'm eventually coding it. Unfortunately at the moment it's blocked by a [bug in postgres core](https://www.postgresql.org/message-id/flat/f86dde87-fef4-71eb-0480-62754aaca01b%40imap.cc#f86dde87-fef4-71eb-0480-62754aaca01b@imap.cc). I hope it will be fixed in the next bugfix release (9th Aug 2018), and parallel-enabled version of argm will probably be released in the same month.

**Comment by bashtanov** [comment]
I've opened https://github.com/bashtanov/argm/pull/8 for both parallelization and PG 10+ compatibility. @jeffjanes I would appreciate if you could have a look.
